### ISSUE TITLE
File.seek() terminates ungracefully on incorrect origin for -m32mscoff and -m64

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/phobos#10589]
### Description

The origin parameter to File.seek() should only accept SEEK_STEP, SEEK_CUR or SEEK_END. 
When a different int is passed, an exception is correctly thrown when compiled with -m32. 
However, on Windows 10 at least, when compiled with either -m32mscoff or -m64, the process terminates without any message whatsoever.

```d
import std;

void main()
{       
        auto deleteme = "deleteme";
        auto f = File(deleteme, "wb+");
        scope(exit) { f.close(); std.file.remove(deleteme); }
        f.seek(0, 3);   // Should throw.

        writeln("Ending gracefully."); // Never seen.
}
```

**Comment by thewilsonator** [comment]
Fixed by #6948
